- name : Configure Docker on EC2 Instances
  hosts : [kube-server]
  become: true
  connection : ssh
  tasks :
  - name: create new deployment
    command : kubectl create -f /home/ubuntu/deployment.yml

  - name : create a service
    command : kubectl create -f /home/ubuntu/service.yml
 
