- name : Configure Docker on EC2 Instances
  hosts : [kube-server]
  become: true
  connection : ssh
  tasks :
  - name: Copying deployment file to kubernete server
    command: cp /var/lib/jenkins/workspace/Project3_Healthcare-pipeline/deployment.yml /home/ubuntu/

  - name: copy service file
    command: cp /var/lib/jenkins/workspace/Project3_Healthcare-pipeline/service.yml /home/ubuntu/


  - name: create new deployment
    command : kubectl create -f /home/ubuntu/deployment/yml

  - name : create a service
    command : kubectl create -f /home/ubuntu/service.yml
 
